In [1]:
import pandas as pd
import numpy as np

file_path = '../data/warfarin.csv'

try:
    df = pd.read_csv(file_path)

    # Check the dimensions of the dataset
    print("Dataset shape:")
    print(df.shape)

    # Display the first 5 rows to confirm it loaded correctly
    print("\nFirst 5 rows:")
    display(df.head())
    
except Exception as e:
    print(f"An error occurred: {e}")
    print("\nPlease double-check that the file 'warfarin.csv' is saved correctly inside the 'data' folder.")

Dataset shape:
(843, 69)

First 5 rows:

,PharmGKB Subject ID,Gender,Race,Ethnicity,Age,Height (cm),Weight (kg),Indication for Warfarin Treatment,Comorbidities,Medications,...,VKORC1-1639.1,VKORC1-1639.2,VKORC1-1639.3,VKORC1-1639.4,VKORC1-1639.5,VKORC1-1639.6,VKORC1-1639.7,VKORC1-1639.8,VKORC1-1639.9,VKORC1-1639.10
0,PA128919639,male,White,Not Hispanic or Latino,60 - 69,170.18,103.4,Pulmonary Embolism,Diabetes;Hypothyroidism,levothyroxine;metformin,...,0,1,0,0,0,0,0,0,0.0,0.0
1,PA128919639,male,White,Not Hispanic or Latino,60 - 69,170.18,103.4,Pulmonary Embolism,Diabetes;Hypothyroidism,levothyroxine;metformin,...,0,1,0,0,0,0,0,0,0.0,0.0
2,PA128919639,male,White,Not Hispanic or Latino,60 - 69,170.18,103.4,Pulmonary Embolism,Diabetes;Hypothyroidism,levothyroxine;metformin,...,0,1,0,0,0,0,0,0,0.0,0.0
3,PA128919639,male,White,Not Hispanic or Latino,60 - 69,170.18,103.4,Pulmonary Embolism,Diabetes;Hypothyroidism,levothyroxine;metformin,...,0,1,0,0,0,0,0,0,0.0,0.0
4,PA128919639,male,White,Not Hispanic or Latino,60 - 69,170.18,103.4,Pulmonary Embolism,Diabetes;Hypothyroidism,levothyroxine;metformin,...,0,1,0,0,0,0,0,0,0.0,0.0

In [2]:
import xgboost as xgb

# 1. Define Clinical Rules (1 = Up, -1 = Down, 0 = Ignore)
# Assuming your X_train columns are: ['Age', 'Weight_kg', 'Height_cm', 'Serum_Creatinine', 'Calculated_CrCl', 'HLA_A_32_01_Risk', 'agr_Group_II_Mutation', 'Gender_Male']
# Adjust this tuple to exactly match the order of your columns!
monotone_tuple = (
    -1,  # Age: Older = Less Drug
     1,  # Weight: Heavier = More Drug
     0,  # Height: No strict monotonic rule
    -1,  # Serum Creatinine: Higher = Less Drug
     1,  # CrCl: Better clearance = More Drug
    -1,  # HLA Toxicity Risk: Positive = Less Drug
     1,  # agr Mutation: Positive = More Drug (Resistance)
     0   # Gender: No strict monotonic rule
)

# 2. Build the Ultimate XGBoost Model
vancomycin_model = xgb.XGBRegressor(
    objective='reg:tweedie',           # MATH RULE: NEVER predict < 0
    tweedie_variance_power=1.5,        # Standard for healthcare data
    monotone_constraints=monotone_tuple, # BIOLOGY RULE: Obey clinical logic
    n_estimators=150,
    learning_rate=0.05,
    max_depth=4 # Keep trees shallow to prevent overfitting
)

# 3. Train the model
vancomycin_model.fit(X_train, y_train)

# 4. Save your new, flawless model
import joblib
joblib.dump(vancomycin_model, 'vancomycin_xgb_model_v1.pkl')

NameError: name 'X_train' is not defined

In [ ]:
# Get a high-level summary of the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 843 entries, 0 to 842
Data columns (total 69 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   PharmGKB Subject ID                                              843 non-null    object
 1   Gender                                                           843 non-null    object
 2   Race                                                             843 non-null    object
 3   Ethnicity                                                        843 non-null    object
 4   Age                                                              843 non-null    object
 5   Height (cm)                                                      843 non-null    float64
 6   Weight (kg)                                                      843 non-null    float64
 7   Indication for Warfarin Treatment                                843 non-null    object
 8   Comorbidities                                                    318 non-null    object
 9   Medications                                                      843 non-null    object
 10  Target INR                                                       843 non-null    float64
 11  Measured INR                                                     843 non-null    float64
 12  Therapeutic Dose of Warfarin                                     843 non-null    float64
 13  INR on Reported Therapeutic Dose of Warfarin                     843 non-null    float64
 14  Current Smoker                                                   843 non-null    int64
 15  CYP2C9 genotypes                                                 843 non-null    object
 16  Genotyped QC                                                     843 non-null    object
 17  VKORC1 genotype: -1639 G>A (3673); chr16:31015190; rs9923231     843 non-null    object
 18  VKORC1 QC genotype: -1639 G>A (3673); chr16:31015190; rs9923231  843 non-null    object
 19  VKORC1 genotype: 497T>G (5808); chr16:31013055; rs2884737        843 non-null    object
 20  VKORC1 QC genotype: 497T>G (5808); chr16:31013055; rs2884737     843 non-null    object
 21  VKORC1 genotype: 1173 C>T(6484); chr16:31012379; rs9934438       843 non-null    object
 22  VKORC1 QC genotype: 1173 C>T(6484); chr16:31012379; rs9934438    843 non-null    object
 23  VKORC1 genotype: 1542G>C (6853); chr16:31012010; rs8050894       843 non-null    object
 24  VKORC1 QC genotype: 1542G>C (6853); chr16:31012010; rs8050894    843 non-null    object
 25  VKORC1 genotype: 3730 G>A (9041); chr16:31009822; rs2359612      843 non-null    object
 26  VKORC1 QC genotype: 3730 G>A (9041); chr16:31009822; rs2359612   843 non-null    object
 27  VKORC1 genotype: 2255C>T (7566); chr16:31011297; rs7294          843 non-null    object
 28  VKORC1 QC genotype: 2255C>T (7566); chr16:31011297; rs7294       843 non-null    object
 29  VKORC1 genotype: -4451 C>A (861); chr16:31018002; rs17708472     843 non-null    object
 30  VKORC1 QC genotype: -4451 C>A (861); chr16:31018002; rs17708472  843 non-null    object
 31  CYP2C9 consensus                                                 843 non-null    object
 32  VKORC1 -1639 G>A consensus                                       843 non-null    object
 33  VKORC1 497 T>G consensus                                         843 non-null    object
 34  VKORC1 1173 C>T consensus                                        843 non-null    object
 35  VKORC1 1542 G>C consensus                                        843 non-null    object
 36  VKORC1 3730 G>A consensus                                        843 non-null    object
 37  VKORC1 2255 C>T consensus                                        843 non-null    object
 38  VKORC1 -4451 C>A consensus                                       843 non-null    object
 39  CYP2C9 *1/*1                                                     843 non-null    int64
 40  CYP2C9 *1/*2                                                     843 non-null    int64
 41  CYP2C9 *1/*3                                                     843 non-null    int64
 42  CYP2C9 *2/*2                                                     843 non-null    int64
 43  CYP2C9 *2/*3                                                     843 non-null    int64
 44  CYP2C9 *3/*3                                                     843 non-null    int64
 45  CYP2C9geno                                                       843 non-null    object
 46  CYP2C9 *1/*1.1                                                   843 non-null    int64
 47  CYP2C9 *1/*2.1                                                   843 non-null    int64
 48  CYP2C9 *1/*3.1                                                   843 non-null    int64
 49  CYP2C9 *2/*2.1                                                   843 non-null    int64
 50  CYP2C9 *2/*3.1                                                   843 non-null    int64
 51  CYP2C9 *3/*3.1                                                   843 non-null    int64
 52  CYP2C9 *1/*1.2                                                   843 non-null    int64
 53  CYP2C9 *1/*2.2                                                   843 non-null    int64
 54  CYP2C9 *1/*3.2                                                   843 non-null    int64
 55  CYP2C9 *2/*2.2                                                   843 non-null    int64
 56  CYP2C9 *2/*3.2                                                   843 non-null    int64
 57  CYP2C9 *3/*3.2                                                   843 non-null    int64
 58  VKORC1-1639                                                      843 non-null    object
 59  VKORC1-1639.1                                                    843 non-null    int64
 60  VKORC1-1639.2                                                    843 non-null    int64
 61  VKORC1-1639.3                                                    843 non-null    int64
 62  VKORC1-1639.4                                                    843 non-null    int64
 63  VKORC1-1639.5                                                    843 non-null    int64
 64  VKORC1-1639.6                                                    843 non-null    int64
 65  VKORC1-1639.7                                                    843 non-null    int64
 66  VKORC1-1639.8                                                    843 non-null    int64
 67  VKORC1-1639.9                                                    842 non-null    float64
 68  VKORC1-1639.10                                                   842 non-null    float64
dtypes: float64(8), int64(27), object(34)
memory usage: 454.6+ KB

In [ ]:
# Calculate the number of missing values for each column
missing_values = df.isnull().sum()

# Filter and display only the columns that have one or more missing values
print("Columns with missing values:")
print(missing_values[missing_values > 0])

Columns with missing values:
Comorbidities     525
VKORC1-1639.9       1
VKORC1-1639.10      1
dtype: int64

In [ ]:
# Print the shape of the DataFrame before cleaning
print(f"Shape before cleaning: {df.shape}")

# Step 1: Drop the 'Comorbidities' column
df.drop(columns=['Comorbidities'], inplace=True)
print("Dropped 'Comorbidities' column.")

# Step 2 & 3: Drop rows where our target variable or the minor columns are missing
columns_to_check = ['Therapeutic Dose of Warfarin', 'VKORC1-1639.9', 'VKORC1-1639.10']
df.dropna(subset=columns_to_check, inplace=True)
print("Dropped rows with missing values in key columns.")

# --- VERIFICATION ---
# Verify the shape of the DataFrame after cleaning
print(f"Shape after cleaning: {df.shape}")

# Verify that there are no more missing values
print("\nMissing values count after cleaning:")
print(df.isnull().sum().sum())

Shape before cleaning: (843, 69)
Dropped 'Comorbidities' column.
Dropped rows with missing values in key columns.
Shape after cleaning: (842, 68)

Missing values count after cleaning:
0

In [ ]:
# Feature Engineering: Convert 'Age' column from ranges to a numerical value

# First, let's create a copy of our DataFrame to avoid any warnings
df_processed = df.copy()

# This function will convert an age string (e.g., '60 - 69') to its average (65)
def convert_age(age_str):
    if age_str == '90 or older':
        return 90
    else:
        # Split the string '60 - 69' into ['60', '-', '69'], take the first part '60' and add 5
        return int(age_str.split(' ')[0]) + 5

# Apply this function to the entire 'Age' column
df_processed['Age'] = df_processed['Age'].apply(convert_age)


# --- VERIFICATION ---
# Display the first few values of the updated 'Age' column to see the change
print("Data types of columns after converting Age:")
print(df_processed[['Age', 'Gender', 'Race']].dtypes)

print("\nFirst 5 rows of the updated 'Age' column:")
print(df_processed['Age'].head())

Data types of columns after converting Age:
Age        int64
Gender    object
Race      object
dtype: object

First 5 rows of the updated 'Age' column:
0    65
1    65
2    65
3    65
4    65
Name: Age, dtype: int64

In [ ]:
import pandas as pd

# Let's find the exact names of the key genetic columns
cyp2c9_col = 'CYP2C9 genotypes'
# The VKORC1 column name is very long, so we find it programmatically
vkorc1_col = [col for col in df_processed.columns if 'VKORC1 genotype: -1639 G>A' in col][0]

# The two main genetic columns we need to convert
genetic_cols_to_encode = [cyp2c9_col, vkorc1_col]

print(f"Encoding the following columns:\n1. {cyp2c9_col}\n2. {vkorc1_col}\n")

# Apply one-hot encoding using pd.get_dummies
df_genetics_encoded = pd.get_dummies(df_processed[genetic_cols_to_encode])

# Join the new encoded columns back to our main dataframe
df_processed = pd.concat([df_processed, df_genetics_encoded], axis=1)

# Drop the original text-based genetic columns now that we have the encoded versions
df_processed.drop(columns=genetic_cols_to_encode, inplace=True)


# --- VERIFICATION ---
# Display the first 5 rows of our dataframe to see the new columns
print("DataFrame head with new genetic columns:")
display(df_processed.head())

print(f"\nTotal number of columns has now increased to: {df_processed.shape[1]}")

Encoding the following columns:
1. CYP2C9 genotypes
2. VKORC1 genotype: -1639 G>A (3673); chr16:31015190; rs9923231

DataFrame head with new genetic columns:

,PharmGKB Subject ID,Gender,Race,Ethnicity,Age,Height (cm),Weight (kg),Indication for Warfarin Treatment,Medications,Target INR,...,VKORC1-1639.7,VKORC1-1639.8,VKORC1-1639.9,VKORC1-1639.10,CYP2C9 genotypes_CYP2C9 *1/*1,CYP2C9 genotypes_CYP2C9 *1/*2,CYP2C9 genotypes_CYP2C9 *1/*3,VKORC1 genotype: -1639 G>A (3673); chr16:31015190; rs9923231_A/A,VKORC1 genotype: -1639 G>A (3673); chr16:31015190; rs9923231_A/G,VKORC1 genotype: -1639 G>A (3673); chr16:31015190; rs9923231_G/G
0,PA128919639,male,White,Not Hispanic or Latino,65,170.18,103.4,Pulmonary Embolism,levothyroxine;metformin,2.5,...,0,0,0.0,0.0,False,True,False,False,True,False
1,PA128919639,male,White,Not Hispanic or Latino,65,170.18,103.4,Pulmonary Embolism,levothyroxine;metformin,2.5,...,0,0,0.0,0.0,False,True,False,False,True,False
2,PA128919639,male,White,Not Hispanic or Latino,65,170.18,103.4,Pulmonary Embolism,levothyroxine;metformin,2.5,...,0,0,0.0,0.0,False,True,False,False,True,False
3,PA128919639,male,White,Not Hispanic or Latino,65,170.18,103.4,Pulmonary Embolism,levothyroxine;metformin,2.5,...,0,0,0.0,0.0,False,True,False,False,True,False
4,PA128919639,male,White,Not Hispanic or Latino,65,170.18,103.4,Pulmonary Embolism,levothyroxine;metformin,2.5,...,0,0,0.0,0.0,False,True,False,False,True,False

Total number of columns has now increased to: 72

In [ ]:
# Identify remaining categorical columns to encode
cols_to_encode = [
    'Race',
    'Ethnicity',
    'Indication for Warfarin Treatment',
    'Gender'
]

print("Encoding the following columns with one-hot encoding:")
for col in cols_to_encode:
    print(f"- {col}")

# Apply one-hot encoding
df_encoded = pd.get_dummies(df_processed[cols_to_encode])

# Join the new encoded columns back to our main dataframe
df_processed = pd.concat([df_processed, df_encoded], axis=1)

# Drop the original text-based columns
df_processed.drop(columns=cols_to_encode, inplace=True)

# --- VERIFICATION ---
print(f"\nDataFrame now has {df_processed.shape[1]} columns.")
print("Verifying the first 5 rows with all new columns:")
display(df_processed.head())

Encoding the following columns with one-hot encoding:
- Race
- Ethnicity
- Indication for Warfarin Treatment
- Gender

DataFrame now has 76 columns.
Verifying the first 5 rows with all new columns:

,PharmGKB Subject ID,Age,Height (cm),Weight (kg),Medications,Target INR,Measured INR,Therapeutic Dose of Warfarin,INR on Reported Therapeutic Dose of Warfarin,Current Smoker,...,VKORC1 genotype: -1639 G>A (3673); chr16:31015190; rs9923231_A/G,VKORC1 genotype: -1639 G>A (3673); chr16:31015190; rs9923231_G/G,Race_White,Ethnicity_Not Hispanic or Latino,Indication for Warfarin Treatment_Atrial Fibrillation,Indication for Warfarin Treatment_Deep Vein Thrombosis,Indication for Warfarin Treatment_Mechanical Heart Valve,Indication for Warfarin Treatment_Pulmonary Embolism,Gender_female,Gender_male
0,PA128919639,65,170.18,103.4,levothyroxine;metformin,2.5,2.7,49.0,2.7,0,...,True,False,True,True,False,False,False,True,False,True
1,PA128919639,65,170.18,103.4,levothyroxine;metformin,2.5,2.7,49.0,2.7,0,...,True,False,True,True,False,False,False,True,False,True
2,PA128919639,65,170.18,103.4,levothyroxine;metformin,2.5,2.7,49.0,2.7,0,...,True,False,True,True,False,False,False,True,False,True
3,PA128919639,65,170.18,103.4,levothyroxine;metformin,2.5,2.7,49.0,2.7,0,...,True,False,True,True,False,False,False,True,False,True
4,PA128919639,65,170.18,103.4,levothyroxine;metformin,2.5,2.7,49.0,2.7,0,...,True,False,True,True,False,False,False,True,False,True

In [ ]:
# Identify any remaining non-numerical columns (like IDs and complex text)
object_cols = df_processed.select_dtypes(include=['object']).columns
print(f"Remaining non-numerical columns to be dropped: \n{list(object_cols)}")

# Drop these final columns
df_processed.drop(columns=object_cols, inplace=True)

# --- FINAL PREPARATION: Define Features (X) and Target (y) ---

# Our target 'y' is the column we want to predict
y = df_processed['Therapeutic Dose of Warfarin']

# Our features 'X' are all the other columns
X = df_processed.drop(columns=['Therapeutic Dose of Warfarin'])

# --- VERIFICATION ---
print(f"\nFinal shape of feature data (X): {X.shape}")
print(f"Final shape of target data (y): {y.shape}")
print("\nFirst 5 rows of the final features (X):")
display(X.head())

print("\nFirst 5 values of the final target (y):")
print(y.head())

Remaining non-numerical columns to be dropped:
['PharmGKB Subject ID', 'Medications', 'Genotyped QC', 'VKORC1 QC genotype: -1639 G>A (3673); chr16:31015190; rs9923231', 'VKORC1 genotype: 497T>G (5808); chr16:31013055; rs2884737', 'VKORC1 QC genotype: 497T>G (5808); chr16:31013055; rs2884737', 'VKORC1 genotype: 1173 C>T(6484); chr16:31012379; rs9934438', 'VKORC1 QC genotype: 1173 C>T(6484); chr16:31012379; rs9934438', 'VKORC1 genotype: 1542G>C (6853); chr16:31012010; rs8050894', 'VKORC1 QC genotype: 1542G>C (6853); chr16:31012010; rs8050894', 'VKORC1 genotype: 3730 G>A (9041); chr16:31009822; rs2359612', 'VKORC1 QC genotype: 3730 G>A (9041); chr16:31009822; rs2359612', 'VKORC1 genotype: 2255C>T (7566); chr16:31011297; rs7294', 'VKORC1 QC genotype: 2255C>T (7566); chr16:31011297; rs7294', 'VKORC1 genotype: -4451 C>A (861); chr16:31018002; rs17708472', 'VKORC1 QC genotype: -4451 C>A (861); chr16:31018002; rs17708472', 'CYP2C9 consensus', 'VKORC1 -1639 G>A consensus', 'VKORC1 497 T>G consensus', 'VKORC1 1173 C>T consensus', 'VKORC1 1542 G>C consensus', 'VKORC1 3730 G>A consensus', 'VKORC1 2255 C>T consensus', 'VKORC1 -4451 C>A consensus', 'CYP2C9geno', 'VKORC1-1639']

Final shape of feature data (X): (842, 49)
Final shape of target data (y): (842,)

First 5 rows of the final features (X):

,Age,Height (cm),Weight (kg),Target INR,Measured INR,INR on Reported Therapeutic Dose of Warfarin,Current Smoker,CYP2C9 *1/*1,CYP2C9 *1/*2,CYP2C9 *1/*3,...,VKORC1 genotype: -1639 G>A (3673); chr16:31015190; rs9923231_A/G,VKORC1 genotype: -1639 G>A (3673); chr16:31015190; rs9923231_G/G,Race_White,Ethnicity_Not Hispanic or Latino,Indication for Warfarin Treatment_Atrial Fibrillation,Indication for Warfarin Treatment_Deep Vein Thrombosis,Indication for Warfarin Treatment_Mechanical Heart Valve,Indication for Warfarin Treatment_Pulmonary Embolism,Gender_female,Gender_male
0,65,170.18,103.4,2.5,2.7,2.7,0,0,1,0,...,True,False,True,True,False,False,False,True,False,True
1,65,170.18,103.4,2.5,2.7,2.7,0,0,1,0,...,True,False,True,True,False,False,False,True,False,True
2,65,170.18,103.4,2.5,2.7,2.7,0,0,1,0,...,True,False,True,True,False,False,False,True,False,True
3,65,170.18,103.4,2.5,2.7,2.7,0,0,1,0,...,True,False,True,True,False,False,False,True,False,True
4,65,170.18,103.4,2.5,2.7,2.7,0,0,1,0,...,True,False,True,True,False,False,False,True,False,True

First 5 values of the final target (y):
0    49.0
1    49.0
2    49.0
3    49.0
4    49.0
Name: Therapeutic Dose of Warfarin, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import numpy as np

# Step 1: Split the data into training (80%) and testing (20%) sets
# random_state=42 is a number we use to ensure the split is the same every time we run the code
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Initialize and train the Linear Regression model
# The .fit() function is where the model 'learns' from the data
print("Training the Linear Regression model...")
model = LinearRegression()
model.fit(X_train, y_train)
print("Model training complete.")

# Step 3: Make predictions on the unseen test data
y_pred = model.predict(X_test)

# Step 4: Evaluate the model's performance
# We use Root Mean Squared Error (RMSE) to see how far off our predictions are on average.
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"\n--- Model Evaluation ---")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")

Training the Linear Regression model...
Model training complete.

--- Model Evaluation ---
Root Mean Squared Error (RMSE): 4.64

In [ ]:
import joblib

# Define the path and filename for our model
model_filename = '../models/linear_regression_base_v1.pkl'

# Save the trained model to the file
joblib.dump(model, model_filename)

print(f"Model saved successfully to: {model_filename}")

Model saved successfully to: ../models/linear_regression_base_v1.pkl

In [ ]:
# Load the model from the file
loaded_model = joblib.load('../models/linear_regression_base_v1.pkl')

# Let's test it by making a prediction on the first row of our test data
first_patient_data = X_test.iloc[0]
predicted_dose = loaded_model.predict([first_patient_data])

print("Successfully loaded the model and made a test prediction.")
print(f"Data for first patient in test set: \n{first_patient_data}")
print(f"\nPredicted dose for this patient: {predicted_dose[0]:.2f} mg/week")

Successfully loaded the model and made a test prediction.
Data for first patient in test set:
Age                                                                     65
Height (cm)                                                         167.64
Weight (kg)                                                          130.2
Target INR                                                             2.5
Measured INR                                                           2.7
INR on Reported Therapeutic Dose of Warfarin                           2.7
Current Smoker                                                           0
CYP2C9 *1/*1                                                             1
CYP2C9 *1/*2                                                             0
CYP2C9 *1/*3                                                             0
CYP2C9 *2/*2                                                             0
CYP2C9 *2/*3                                                             0
CYP2C9 *3/*3                                                             0
CYP2C9 *1/*1.1                                                           1
CYP2C9 *1/*2.1                                                           0
CYP2C9 *1/*3.1                                                           0
CYP2C9 *2/*2.1                                                           0
CYP2C9 *2/*3.1                                                           0
CYP2C9 *3/*3.1                                                           0
CYP2C9 *1/*1.2                                                           1
CYP2C9 *1/*2.2                                                           0
CYP2C9 *1/*3.2                                                           0
CYP2C9 *2/*2.2                                                           0
CYP2C9 *2/*3.2                                                           0
CYP2C9 *3/*3.2                                                           0
VKORC1-1639.1                                                            1
VKORC1-1639.2                                                            0
VKORC1-1639.3                                                            0
VKORC1-1639.4                                                            0
VKORC1-1639.5                                                            0
VKORC1-1639.6                                                            0
VKORC1-1639.7                                                            0
VKORC1-1639.8                                                            0
VKORC1-1639.9                                                          0.0
VKORC1-1639.10                                                         0.0
CYP2C9 genotypes_CYP2C9 *1/*1                                         True
CYP2C9 genotypes_CYP2C9 *1/*2                                        False
CYP2C9 genotypes_CYP2C9 *1/*3                                        False
VKORC1 genotype: -1639 G>A (3673); chr16:31015190; rs9923231_A/A     False
VKORC1 genotype: -1639 G>A (3673); chr16:31015190; rs9923231_A/G     False
VKORC1 genotype: -1639 G>A (3673); chr16:31015190; rs9923231_G/G      True
Race_White                                                            True
Ethnicity_Not Hispanic or Latino                                      True
Indication for Warfarin Treatment_Atrial Fibrillation                 True
Indication for Warfarin Treatment_Deep Vein Thrombosis               False
Indication for Warfarin Treatment_Mechanical Heart Valve             False
Indication for Warfarin Treatment_Pulmonary Embolism                 False
Gender_female                                                         True
Gender_male                                                          False
Name: 493, dtype: object

Predicted dose for this patient: 54.30 mg/week

c:\Users\aniru\OneDrive\Desktop\DosagePredictAI\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
# Clean up the column names in X
X.columns = ["".join (c if c.isalnum() else '_' for c in str(x)) for x in X.columns]

# Let's check the first few new column names to see the change
print("Cleaned feature names (first 10):")
print(X.columns[:10].tolist())

Cleaned feature names (first 10):
['Age', 'Height__cm_', 'Weight__kg_', 'Target_INR', 'Measured_INR', 'INR_on_Reported_Therapeutic_Dose_of_Warfarin', 'Current_Smoker', 'CYP2C9__1__1', 'CYP2C9__1__2', 'CYP2C9__1__3']

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import numpy as np

# Step 1: Split the data again (using our cleaned 'X')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Initialize and train the Random Forest model
# n_estimators=100 means we are creating a 'committee' of 100 decision trees
print("Training the Random Forest model...")
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
print("Model training complete.")

# Step 3: Make predictions on the test set
y_pred_rf = rf_model.predict(X_test)

# Step 4: Evaluate the new model's performance
mse_rf = mean_squared_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mse_rf)

print(f"\n--- Model Evaluation ---")
print(f"Linear Regression RMSE (Baseline): 4.64")
print(f"Random Forest Regressor RMSE:      {rmse_rf:.2f}")

Training the Random Forest model...
Model training complete.

--- Model Evaluation ---
Linear Regression RMSE (Baseline): 4.64
Random Forest Regressor RMSE:      0.14

In [ ]:
import joblib

# Define the path and filename for our new model
model_filename = '../models/random_forest_enhanced_v1.pkl'

# Save the trained Random Forest model to the file
# Note: We are saving the 'rf_model' variable this time
joblib.dump(rf_model, model_filename)

print(f"Random Forest model saved successfully to: {model_filename}")

Random Forest model saved successfully to: ../models/random_forest_enhanced_v1.pkl

In [ ]:
# --- Building a TRUE 'Clinical-Only' Base Model ---

# A better way to identify all genomic columns (anything with CYP2C9 or VKORC1 in the name)
genomic_cols_to_drop = [col for col in X.columns if 'CYP2C9' in col or 'VKORC1' in col]

X_clinical_true = X.drop(columns=genomic_cols_to_drop)

print(f"Number of original features: {X.shape[1]}")
print(f"Number of genomic features to drop: {len(genomic_cols_to_drop)}")
print(f"Number of remaining true clinical features: {X_clinical_true.shape[1]}")

# Split the TRUE clinical-only data
X_train_cli, X_test_cli, y_train_cli, y_test_cli = train_test_split(X_clinical_true, y, test_size=0.2, random_state=42)

# Train a new Random Forest model on this corrected data
print("\nTraining the TRUE Clinical-Only Random Forest model...")
rf_model_clinical_true = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model_clinical_true.fit(X_train_cli, y_train_cli)
print("Model training complete.")

# --- RE-SAVE THE BASE MODEL AND ITS COLUMNS ---
# This will overwrite our previous, slightly incorrect base model
joblib.dump(rf_model_clinical_true, '../models/random_forest_base_v1.pkl')
joblib.dump(X_clinical_true.columns.tolist(), '../models/base_model_columns.pkl')
print("\nCorrected Base Model and its columns have been saved.")

Number of original features: 49
Number of genomic features to drop: 34
Number of remaining true clinical features: 15

Training the TRUE Clinical-Only Random Forest model...
Model training complete.

Corrected Base Model and its columns have been saved.

In [ ]:
import joblib

# Define the path and filename for our base model
model_filename = '../models/random_forest_base_v1.pkl'

# Save the trained clinical-only model to the file
joblib.dump(rf_model_clinical_true, model_filename)

print(f"Clinical-Only Base Model saved successfully to: {model_filename}")

Clinical-Only Base Model saved successfully to: ../models/random_forest_base_v1.pkl

In [ ]:
import joblib

# Save the first row of your test set as a sample for the API
# We use X_test because the model has never been trained on this data.
joblib.dump(X_test.iloc[0:1], '../models/sample_patient_test.pkl')

print("Sample patient data saved to 'models/sample_patient_test.pkl'")

Sample patient data saved to 'models/sample_patient_test.pkl'

In [ ]:
import joblib

# Define the path to save the column list (using the correct relative path)
column_list_path = '../models/model_columns.pkl'

# Save the list of columns from your final feature DataFrame 'X'
joblib.dump(X.columns.tolist(), column_list_path)

print(f"Model columns saved successfully to: {column_list_path}")

Model columns saved successfully to: ../models/model_columns.pkl

In [ ]:
import joblib

# X_clinical is the DataFrame with only clinical features we created earlier
# If this variable is not in memory, you may need to "Run All Above"

# Define the path and save the column list
base_columns_path = '../models/base_model_columns.pkl'
joblib.dump(X_clinical_true.columns.tolist(), base_columns_path)

print(f"Base model columns saved successfully to: {base_columns_path}")

Base model columns saved successfully to: ../models/base_model_columns.pkl

In [ ]:
import joblib
import os

# Define the correct relative path to the 'models' folder
# (Up one level from 'notebooks' folder)
models_dir = '../models'
os.makedirs(models_dir, exist_ok=True) 

# --- SAVE THE ENHANCED MODEL AND ITS COLUMNS ---
# These names come from your Cell 2
joblib.dump(rf_model, os.path.join(models_dir, 'random_forest_enhanced_v1.pkl'))
joblib.dump(list(X_train.columns), os.path.join(models_dir, 'model_columns.pkl'))

# --- SAVE THE BASE MODEL AND ITS COLUMNS ---
# These names come from the code you provided earlier
joblib.dump(rf_model_clinical_true, os.path.join(models_dir, 'random_forest_base_v1.pkl'))
joblib.dump(list(X_clinical_true.columns), os.path.join(models_dir, 'base_model_columns.pkl'))

print(f"--- All 4 files saved successfully into the '{models_dir}' folder! ---")

--- All 4 files saved successfully into the '../models' folder! ---

In [ ]:
!pip install pandas numpy scikit-learn matplotlib seaborn

Requirement already satisfied: pandas in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (1.7.2)
Requirement already satisfied: matplotlib in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (3.10.6)
Requirement already satisfied: seaborn in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from scikit-learn) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import joblib

# 1. Load the Base Clinical Dataset (Pima Indians Diabetes)
print("Downloading dataset...")
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigree', 'Age', 'Outcome']
df = pd.read_csv(url, names=columns)

# 2. Inject the Genomic Twist (TCF7L2 Gene Variant)
# To keep your project's unique "Genomic" theme, we synthetically add this gene.
# High-risk variant is highly correlated with the diabetic outcome.
np.random.seed(42)
df['TCF7L2_Risk_Variant'] = np.where(
    df['Outcome'] == 1, 
    np.random.choice([1, 0], size=len(df), p=[0.7, 0.3]), # 70% of diabetics have it
    np.random.choice([1, 0], size=len(df), p=[0.3, 0.7])  # Only 30% of healthy have it
)

# 3. Prepare Data for Training
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split into 80% training, 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Train the Classification Model
print("Training Diabetes Classification Model...")
clf = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
clf.fit(X_train, y_train)

# Test Accuracy
accuracy = clf.score(X_test, y_test)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

# 5. Export the Models for Flask
joblib.dump(clf, 'diabetes_model_v1.pkl')
joblib.dump(list(X.columns), 'diabetes_model_columns.pkl')
print("✅ SUCCESS: Saved 'diabetes_model_v1.pkl' and 'diabetes_model_columns.pkl'")

Downloading dataset...
Training Diabetes Classification Model...
Model Accuracy: 83.12%
✅ SUCCESS: Saved 'diabetes_model_v1.pkl' and 'diabetes_model_columns.pkl'

In [ ]:
import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(2026)

# 1. Define Dataset Size
NUM_PATIENTS = 5000

print(f"Generating {NUM_PATIENTS} virtual patients...")

# 2. Generate Base Clinical Demographics
ages = np.random.randint(18, 90, NUM_PATIENTS)
weights_kg = np.random.uniform(50.0, 140.0, NUM_PATIENTS).round(1)
heights_cm = np.random.uniform(150.0, 195.0, NUM_PATIENTS).round(1)
genders = np.random.choice(['Male', 'Female'], NUM_PATIENTS)
# Serum Creatinine (0.5 to 2.5 mg/dL) representing healthy to poor kidney function
serum_creatinine = np.random.uniform(0.5, 2.5, NUM_PATIENTS).round(2)

# 3. Generate Genomic Markers
# HLA-A*32:01 (Toxicity Risk) - ~5% prevalence
hla_risk = np.random.choice([1, 0], NUM_PATIENTS, p=[0.05, 0.95])
# agr Group II (Bacterial Resistance) - ~15% prevalence
agr_resistance = np.random.choice([1, 0], NUM_PATIENTS, p=[0.15, 0.85])

# Initialize lists to hold calculated values
crcl_list = []
target_doses = []

# 4. The Pharmacokinetic & Pharmacogenomic Engine
for i in range(NUM_PATIENTS):
    age = ages[i]
    wt = weights_kg[i]
    scr = serum_creatinine[i]
    gender = genders[i]
    hla = hla_risk[i]
    agr = agr_resistance[i]

    # --- STEP A: Calculate Creatinine Clearance (Cockcroft-Gault Equation) ---
    crcl = ((140 - age) * wt) / (72 * scr)
    if gender == 'Female':
        crcl *= 0.85
    crcl_list.append(round(crcl, 1))

    # --- STEP B: Calculate Baseline Daily Dose (mg) ---
    # Standard continuous PK estimation based on CrCl and Weight
    # Formula creates a baseline between roughly 10mg/kg to 30mg/kg daily
    base_dose = wt * (10 + (crcl / 10))
    
    # Cap maximum baseline dose for safety (e.g., 4000mg/day)
    if base_dose > 4000:
        base_dose = 4000

    # --- STEP C: Apply Genomic Modifiers ---
    # If High Toxicity Risk, reduce dose by 20%
    if hla == 1:
        base_dose *= 0.80
    
    # If High Bacterial Resistance, increase dose by 15%
    if agr == 1:
        base_dose *= 1.15

    # --- STEP D: Add "Real-World" Clinical Noise ---
    # Add +/- 5% random variance to simulate doctor discretion and rounding
    noise_factor = np.random.normal(0, 0.05)
    final_dose = base_dose * (1 + noise_factor)

    # Round to the nearest 250mg (Standard IV Bag sizes: 500, 750, 1000, 1250, etc.)
    final_dose_rounded = round(final_dose / 250) * 250
    
    # Ensure absolute minimum dose is 500mg
    if final_dose_rounded < 500:
        final_dose_rounded = 500
        
    target_doses.append(final_dose_rounded)

# 5. Compile into a DataFrame
df = pd.DataFrame({
    'Age': ages,
    'Weight_kg': weights_kg,
    'Height_cm': heights_cm,
    'Gender': genders,
    'Serum_Creatinine': serum_creatinine,
    'Calculated_CrCl': crcl_list,
    'HLA_A_32_01_Risk': hla_risk,
    'agr_Group_II_Mutation': agr_resistance,
    'Target_Vancomycin_Dose_mg': target_doses
})

# Convert Gender to numeric (1=Male, 0=Female) for Machine Learning
df['Gender_Male'] = df['Gender'].apply(lambda x: 1 if x == 'Male' else 0)
df = df.drop('Gender', axis=1)

# 6. Export to CSV
csv_filename = "vancomycin_genomic_dataset.csv"
df.to_csv(csv_filename, index=False)

print(f"✅ Success! Dataset exported as '{csv_filename}'.")
print(df.head())

Generating 5000 virtual patients...
✅ Success! Dataset exported as 'vancomycin_genomic_dataset.csv'.
   Age  Weight_kg  Height_cm  Serum_Creatinine  Calculated_CrCl  \
0   19       55.2      151.7              1.16             80.0
1   24       87.7      164.4              0.81            174.4
2   44      126.5      158.3              2.05             82.3
3   74       50.0      187.1              1.67             23.3
4   47       80.4      171.8              2.00             44.1

   HLA_A_32_01_Risk  agr_Group_II_Mutation  Target_Vancomycin_Dose_mg  \
0                 1                      0                        750
1                 0                      0                       2250
2                 0                      0                       2000
3                 0                      0                        750
4                 0                      0                       1250

   Gender_Male
0            1
1            1
2            1
3            0
4            0

In [ ]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from xgboost) (2.3.3)
Requirement already satisfied: scipy in c:\users\aniru\onedrive\desktop\dosagepredictai\venv\lib\site-packages (from xgboost) (1.16.2)

[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# 1. Load the Generated Dataset
print("Loading dataset...")
df = pd.read_csv("vancomycin_genomic_dataset.csv")

# 2. Define Features (X) and Target (y)
# We drop the Target column. All other columns are our clinical and genomic features.
X = df.drop('Target_Vancomycin_Dose_mg', axis=1)
y = df['Target_Vancomycin_Dose_mg']

# Save the column names so our Flask app knows the exact order later
model_columns = list(X.columns)
joblib.dump(model_columns, 'vancomycin_model_columns.pkl')

# 3. Split into Training (80%) and Testing (20%) Sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=2026)

# 4. Initialize the Three Models
models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=2026),
    "XGBoost": XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=2026)
}

# Dictionary to hold the evaluation metrics for the comparison board
results = []

print("\nTraining models and calculating metrics...\n")

# 5. Train and Evaluate Each Model
for name, model in models.items():
    # Train the model
    model.fit(X_train, y_train)
    
    # Make predictions on the unseen test data
    predictions = model.predict(X_test)
    
    # Calculate Metrics
    mae = mean_absolute_error(y_test, predictions)
    rmse = np.sqrt(mean_squared_error(y_test, predictions))
    r2 = r2_score(y_test, predictions) * 100  # Convert to percentage
    
    results.append({
        "Algorithm": name,
        "MAE (mg)": round(mae, 2),
        "RMSE (mg)": round(rmse, 2),
        "Accuracy (R²) %": round(r2, 2)
    })
    
    # Save the Random Forest and XGBoost models for the Web App integration
    if name == "Random Forest":
        joblib.dump(model, 'vancomycin_rf_model_v1.pkl')
    elif name == "XGBoost":
        joblib.dump(model, 'vancomycin_xgb_model_v1.pkl')

# 6. Display the Comparison Leaderboard
results_df = pd.DataFrame(results)
print("=========================================================")
print("🏆 MODEL PERFORMANCE LEADERBOARD (TEST SET EVALUATION) 🏆")
print("=========================================================")
print(results_df.to_string(index=False))
print("=========================================================\n")
print("✅ Random Forest and XGBoost models have been saved as .pkl files!")

Loading dataset...

Training models and calculating metrics...

=========================================================
🏆 MODEL PERFORMANCE LEADERBOARD (TEST SET EVALUATION) 🏆
=========================================================
        Algorithm  MAE (mg)  RMSE (mg)  Accuracy (R²) %
Linear Regression    140.32     207.44            94.14
    Random Forest     97.56     136.31            97.47
          XGBoost     97.11     127.54            97.78
=========================================================

✅ Random Forest and XGBoost models have been saved as .pkl files!

In [ ]:
import pandas as pd
import numpy as np
import xgboost as xgb
import joblib
from sklearn.model_selection import train_test_split

# 1. LOAD DATA DIRECTLY
df = pd.read_csv('../data/vancomycin_genomic_dataset.csv')

# 2. ENFORCE STRICT COLUMNS
expected_columns = [
    'Age', 'Weight_kg', 'Height_cm', 'Serum_Creatinine', 
    'Calculated_CrCl', 'HLA_A_32_01_Risk', 'agr_Group_II_Mutation', 'Gender_Male'
]
X = df[expected_columns]
y = df['Target_Vancomycin_Dose_mg'] # Ensure this matches your CSV column name!

# 3. CREATE TRAINING DATA
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. CLINICAL RULES: 1=Up, -1=Down, 0=Ignore
# Age(-1), Weight(1), Height(0), Scr(-1), CrCl(1), HLA(-1), agr(1), Gender(0)
monotone_tuple = (-1, 1, 0, -1, 1, -1, 1, 0)

# 5. BUILD THE MODEL (Standard Regression + Clinical Rules)
vancomycin_model = xgb.XGBRegressor(
    objective='reg:squarederror',
    monotone_constraints=monotone_tuple,
    n_estimators=200,      # Slightly more trees
    learning_rate=0.1,     # Faster learning rate to reach 2000mg scale
    max_depth=4
)

# 6. TRAIN & SAVE
print("Training final Vancomycin model...")
vancomycin_model.fit(X_train, y_train)

joblib.dump(vancomycin_model, 'vancomycin_xgb_model_v1.pkl')
joblib.dump(expected_columns, 'vancomycin_model_columns.pkl')

print("Saved: vancomycin_xgb_model_v1.pkl")
print("Saved: vancomycin_model_columns.pkl")

Training final Vancomycin model...
Saved: vancomycin_xgb_model_v1.pkl
Saved: vancomycin_model_columns.pkl

In [7]:
import pandas as pd
import lime.lime_tabular
import joblib
import dill  # <-- NEW: Import dill

# ==========================================
# 1. VANCOMYCIN LIME EXPLAINER
# ==========================================
print("Generating Vancomycin LIME Explainer...")
df_vanc = pd.read_csv('../data/vancomycin_genomic_dataset.csv')
vanc_cols = joblib.load('../models/vancomycin/vancomycin_model_columns.pkl')

X_vanc = df_vanc.reindex(columns=vanc_cols, fill_value=0)

vanc_lime_explainer = lime.lime_tabular.LimeTabularExplainer(
    training_data=X_vanc.values,
    feature_names=vanc_cols,
    class_names=['Vancomycin Target Dose'],
    mode='regression'
)

# <-- NEW: Use dill.dump instead of joblib
with open('vancomycin_lime_explainer.pkl', 'wb') as f:
    dill.dump(vanc_lime_explainer, f)
print("✅ Saved: vancomycin_lime_explainer.pkl")

# ==========================================
# 2. WARFARIN LIME EXPLAINER
# ==========================================
print("\nGenerating Warfarin LIME Explainer...")
df_warfarin = pd.read_csv('../data/warfarin.csv')
warfarin_cols = joblib.load('../models/warfarin/base_model_columns.pkl')

X_warfarin = df_warfarin.reindex(columns=warfarin_cols, fill_value=0)

# <-- NEW CRITICAL LINE: Force all text into numbers so LIME can do the math
X_warfarin = X_warfarin.apply(pd.to_numeric, errors='coerce').fillna(0)

warfarin_lime_explainer = lime.lime_tabular.LimeTabularExplainer(
    training_data=X_warfarin.values,
    feature_names=warfarin_cols,
    class_names=['Therapeutic Dose of Warfarin'],
    mode='regression'
)

with open('warfarin_lime_explainer.pkl', 'wb') as f:
    dill.dump(warfarin_lime_explainer, f)
print("✅ Saved: warfarin_lime_explainer.pkl")

Generating Vancomycin LIME Explainer...
✅ Saved: vancomycin_lime_explainer.pkl

Generating Warfarin LIME Explainer...
✅ Saved: warfarin_lime_explainer.pkl

In [2]:
import pandas as pd
from sklearn.mixture import BayesianGaussianMixture
import joblib
import warnings

# Suppress the harmless Windows CPU core warning
warnings.filterwarnings("ignore", message="Could not find the number of physical cores")

# ==========================================
# 1. WARFARIN BAYESIAN MODEL
# ==========================================
print("Training Warfarin Bayesian Network...")
df_warfarin = pd.read_csv('../data/warfarin.csv')
warfarin_cols = joblib.load('../models/warfarin/base_model_columns.pkl') 
X_warfarin = df_warfarin.reindex(columns=warfarin_cols, fill_value=0).apply(pd.to_numeric, errors='coerce').fillna(0)

# Added max_iter=1000 and n_init=3 to fix Convergence Warnings
bgm_warfarin = BayesianGaussianMixture(n_components=3, max_iter=1000, n_init=3, random_state=42)
bgm_warfarin.fit(X_warfarin)
joblib.dump(bgm_warfarin, 'warfarin_bayesian_net.pkl')
print("✅ Saved: warfarin_bayesian_net.pkl")

# ==========================================
# 2. VANCOMYCIN BAYESIAN MODEL
# ==========================================
print("\nTraining Vancomycin Bayesian Network...")
df_vanc = pd.read_csv('../data/vancomycin_genomic_dataset.csv')
vanc_cols = joblib.load('../models/vancomycin/vancomycin_model_columns.pkl')
X_vanc = df_vanc.reindex(columns=vanc_cols, fill_value=0).apply(pd.to_numeric, errors='coerce').fillna(0)

# Added max_iter=1000 and n_init=3 to fix Convergence Warnings
bgm_vanc = BayesianGaussianMixture(n_components=3, max_iter=1000, n_init=3, random_state=42)
bgm_vanc.fit(X_vanc)
joblib.dump(bgm_vanc, 'vancomycin_bayesian_net.pkl')
print("✅ Saved: vancomycin_bayesian_net.pkl")

Training Warfarin Bayesian Network...

c:\Users\aniru\OneDrive\Desktop\DosagePredictAI\venv\Lib\site-packages\sklearn\base.py:1365: ConvergenceWarning: Number of distinct clusters (1) found smaller than n_clusters (3). Possibly due to duplicate points in X.
  return fit_method(estimator, *args, **kwargs)
c:\Users\aniru\OneDrive\Desktop\DosagePredictAI\venv\Lib\site-packages\sklearn\base.py:1365: ConvergenceWarning: Number of distinct clusters (1) found smaller than n_clusters (3). Possibly due to duplicate points in X.
  return fit_method(estimator, *args, **kwargs)
c:\Users\aniru\OneDrive\Desktop\DosagePredictAI\venv\Lib\site-packages\sklearn\base.py:1365: ConvergenceWarning: Number of distinct clusters (1) found smaller than n_clusters (3). Possibly due to duplicate points in X.
  return fit_method(estimator, *args, **kwargs)
c:\Users\aniru\OneDrive\Desktop\DosagePredictAI\venv\Lib\site-packages\sklearn\mixture\_base.py:275: ConvergenceWarning: Best performing initialization did not converge. Try different init parameters, or increase max_iter, tol, or check for degenerate data.
  warnings.warn(

✅ Saved: warfarin_bayesian_net.pkl

Training Vancomycin Bayesian Network...
✅ Saved: vancomycin_bayesian_net.pkl